#!/bin/bash

echo "Building gem..."
rm *.gem
gem build gemspec

echo "Installing gem locally..."
gem install *.gem --no-ri --no-rdoc

rspec --colour --format documentation spec/

rspec_success=$?

# Upload gem to server if the user is jenkins and the tests were all successful
if [ $rspec_success -eq 0 -a $USER == 'jenkins' ]; then
  echo "Uploading gem to server..."
  chown jenkins *.gem
  scp *.gem jenkins@slice:
  ssh jenkins@slice "mv *.gem /var/www/gems-repo/gems/ && gem generate_index -d /var/www/gems-repo/ --update"
fi

exit $rspec_success